In [68]:
import numpy as np
import pandas as pd

In [69]:
data = pd.read_csv("Airbnb_Open_Data.csv")

C:\Users\ART\AppData\Local\Temp\ipykernel_13896\180275767.py:1: DtypeWarning: Columns (0: license) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("Airbnb_Open_Data.csv")

In [70]:
df = pd.DataFrame(data)

In [71]:
df

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [72]:
df.shape

(102599, 26)

In [73]:
df.isna().count()

id                                102599
NAME                              102599
host id                           102599
host_identity_verified            102599
host name                         102599
neighbourhood group               102599
neighbourhood                     102599
lat                               102599
long                              102599
country                           102599
country code                      102599
instant_bookable                  102599
cancellation_policy               102599
room type                         102599
Construction year                 102599
price                             102599
service fee                       102599
minimum nights                    102599
number of reviews                 102599
last review                       102599
reviews per month                 102599
review rate number                102599
calculated host listings count    102599
availability 365                  102599
house_rules                       102599
license                           102599
dtype: int64

In [74]:
data.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='str')

## Steps we do to clean data
1. Deleting Redundant columns
2. Renaming Columns
3. Dropping Duplicates
4. Remove the NaN values from Dataset
5. Cleaning individual columns
6. Check for some more transformation
---

### 1. Deleting Redundant Columns

In [75]:
# here we make list of which cols we want and which we want to drop
column_keep = ['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review']
column_drop= ['reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license','id']

In [76]:
print(len(column_keep))
print(len(column_drop))

19
7

In [77]:
data.drop(columns=column_drop, inplace=True)

In [78]:
data.shape

(102599, 19)

In [79]:
df = pd.DataFrame(data)
df

,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/2015
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/2015
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN

### 2. Renaming Columns

In [80]:
data.columns

Index(['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review'],
      dtype='str')

In [81]:
# Preparing dictionary which -- OriginalName : NewName
mapping_dic = {}
for i in data.columns:
    tempName = "_".join(i.split(" ")).lower()
    mapping_dic[i] = " ".join(tempName.split("_")).title()
print(mapping_dic)

{'NAME': 'Name', 'host id': 'Host Id', 'host_identity_verified': 'Host Identity Verified', 'host name': 'Host Name', 'neighbourhood group': 'Neighbourhood Group', 'neighbourhood': 'Neighbourhood', 'lat': 'Lat', 'long': 'Long', 'country': 'Country', 'country code': 'Country Code', 'instant_bookable': 'Instant Bookable', 'cancellation_policy': 'Cancellation Policy', 'room type': 'Room Type', 'Construction year': 'Construction Year', 'price': 'Price', 'service fee': 'Service Fee', 'minimum nights': 'Minimum Nights', 'number of reviews': 'Number Of Reviews', 'last review': 'Last Review'}

In [82]:
data.rename(columns=mapping_dic, inplace=True)
data.columns

Index(['Name', 'Host Id', 'Host Identity Verified', 'Host Name',
       'Neighbourhood Group', 'Neighbourhood', 'Lat', 'Long', 'Country',
       'Country Code', 'Instant Bookable', 'Cancellation Policy', 'Room Type',
       'Construction Year', 'Price', 'Service Fee', 'Minimum Nights',
       'Number Of Reviews', 'Last Review'],
      dtype='str')

### 3. Dropping Duplicates

In [83]:
# It tells for each row either it is duplicated or not
data.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
102594     True
102595     True
102596     True
102597     True
102598     True
Length: 102599, dtype: bool

In [84]:
# More detail
print("First 5 Rows:")
print(data.duplicated().head())
print("\nLast 5 Rows:")
print(data.duplicated().tail())
print("\nTotal Duplicated Rows:")
print(data.duplicated().sum())
print("\nTotal True and Total False Rows:")
print(data.duplicated().value_counts())

First 5 Rows:
0    False
1    False
2    False
3    False
4    False
dtype: bool

Last 5 Rows:
102594    True
102595    True
102596    True
102597    True
102598    True
dtype: bool

Total Duplicated Rows:
541

Total True and Total False Rows:
False    102058
True        541
Name: count, dtype: int64

In [85]:
# Drop duplicate rows
data.drop_duplicates(inplace=True)

In [86]:
print(data.duplicated().sum())
# it will show 0 , means all duplicates removed

0

### 4. Remove NaN Values

In [87]:
data.isna().sum()

Name                        250
Host Id                       0
Host Identity Verified      289
Host Name                   404
Neighbourhood Group          29
Neighbourhood                16
Lat                           8
Long                          8
Country                     532
Country Code                131
Instant Bookable            105
Cancellation Policy          76
Room Type                     0
Construction Year           214
Price                       247
Service Fee                 273
Minimum Nights              400
Number Of Reviews           183
Last Review               15832
dtype: int64

In [88]:
# Last Review has a lot of NULL values, so we drop it
data.drop(columns=["Last Review"], inplace=True)

In [89]:
data.isna().sum()

Name                      250
Host Id                     0
Host Identity Verified    289
Host Name                 404
Neighbourhood Group        29
Neighbourhood              16
Lat                         8
Long                        8
Country                   532
Country Code              131
Instant Bookable          105
Cancellation Policy        76
Room Type                   0
Construction Year         214
Price                     247
Service Fee               273
Minimum Nights            400
Number Of Reviews         183
dtype: int64

In [90]:
# Now Drop all Nan Rows
data.dropna(inplace=True)

In [91]:
data.isna().sum()

Name                      0
Host Id                   0
Host Identity Verified    0
Host Name                 0
Neighbourhood Group       0
Neighbourhood             0
Lat                       0
Long                      0
Country                   0
Country Code              0
Instant Bookable          0
Cancellation Policy       0
Room Type                 0
Construction Year         0
Price                     0
Service Fee               0
Minimum Nights            0
Number Of Reviews         0
dtype: int64

### 5. Cleaning individual columns

In [92]:
data

,Name,Host Id,Host Identity Verified,Host Name,Neighbourhood Group,Neighbourhood,Lat,Long,Country,Country Code,Instant Bookable,Cancellation Policy,Room Type,Construction Year,Price,Service Fee,Minimum Nights,Number Of Reviews
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0
7,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102029,Cozy room in a 2B with backyard access,5155155913,unconfirmed,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,False,flexible,Private room,2018.0,$822,$164,1.0,9.0
102030,An East Williamsburg Delight,71564706996,verified,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,True,moderate,Private room,2015.0,$455,$91,4.0,36.0
102031,Cozy bedroom in williamsburg,83101851929,verified,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,True,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0
102032,Spacious Room w/ 2 Bed,69037598918,unconfirmed,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,False,moderate,Private room,2007.0,$103,$21,7.0,40.0
102040,"Room in Queens, NY, near LGA.",56457739998,verified,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,True,strict,Private room,2022.0,$982,$196,1.0,239.0

In [93]:
# Make 'Host Identity Verified' column values to upper case
data["Host Identity Verified"] = data["Host Identity Verified"].str.upper()
data["Host Identity Verified"]

0         UNCONFIRMED
1            VERIFIED
4            VERIFIED
5            VERIFIED
7         UNCONFIRMED
             ...
102029    UNCONFIRMED
102030       VERIFIED
102031       VERIFIED
102032    UNCONFIRMED
102040       VERIFIED
Name: Host Identity Verified, Length: 99342, dtype: str

In [94]:
# In column 'Instant Bookable' instead of True/False make 1/0
data["Instant Bookable"] = data["Instant Bookable"].apply(lambda x : 1 if x == True else 0)
data["Instant Bookable"]

0         0
1         0
4         0
5         1
7         0
         ..
102029    0
102030    1
102031    1
102032    0
102040    1
Name: Instant Bookable, Length: 99342, dtype: int64

In [95]:
# We don't have consistent number of indexes so we make index consistent
data.reset_index(inplace=True)
data

,index,Name,Host Id,Host Identity Verified,Host Name,Neighbourhood Group,Neighbourhood,Lat,Long,Country,Country Code,Instant Bookable,Cancellation Policy,Room Type,Construction Year,Price,Service Fee,Minimum Nights,Number Of Reviews
0,0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,$966,$193,10.0,9.0
1,1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0
4,7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,$822,$164,1.0,9.0
99338,102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,$455,$91,4.0,36.0
99339,102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0
99340,102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,$103,$21,7.0,40.0
99341,102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,$982,$196,1.0,239.0

In [96]:
# Price column has values as string , we will converti it into int()
data["Price"].head()

0      $966
1      $142
2      $204
3      $577
4    $1,060
Name: Price, dtype: str

In [97]:
data["Price"] = data["Price"].str.replace("$", "")
data["Price"] = data["Price"].str.replace(",", "")
data["Price"] = data["Price"].str.replace(" ", "")

data["Price"]

0         966
1         142
2         204
3         577
4        1060
         ...
99337     822
99338     455
99339    1078
99340     103
99341     982
Name: Price, Length: 99342, dtype: str

In [98]:
data["Price"] = data["Price"].astype(int)
type(data["Price"][0])

numpy.int64

In [99]:
# Save this data as a new CSV Data
data.to_csv("cleaned_data.csv")