In [75]:
import numpy as np
import pandas as pd

In [76]:
data = pd.read_csv("FashionDataset.csv")

In [77]:
df = pd.DataFrame(data)

In [78]:
df.head()

,Unnamed: 0,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women

In [79]:
df.shape

(30758, 8)

## Steps we do to clean data
1. Deleting Redundant columns
2. Renaming Columns
3. Dropping Duplicates
4. Remove the NaN values from Dataset
5. Check for some more transformation
---

### 1. Deleting Redundant columns

In [80]:
data.columns

Index(['Unnamed: 0', 'BrandName', 'Deatils', 'Sizes', 'MRP', 'SellPrice',
       'Discount', 'Category'],
      dtype='str')

In [81]:
# Delete Unnamed column
data.drop(columns=["Unnamed: 0"], inplace=True)

In [82]:
data.columns

Index(['BrandName', 'Deatils', 'Sizes', 'MRP', 'SellPrice', 'Discount',
       'Category'],
      dtype='str')

### 2. Renaming Columns

In [83]:
# Rename the deatils -> details
data.rename(columns={"Deatils" :"Details" },inplace=True)

In [84]:
data.columns

Index(['BrandName', 'Details', 'Sizes', 'MRP', 'SellPrice', 'Discount',
       'Category'],
      dtype='str')

### 3. Dropping Duplicates

In [85]:
# It will shows us how many rows are duplicated
data.duplicated().sum()

np.int64(2827)

In [86]:
data.drop_duplicates(inplace=True)

In [87]:
data.duplicated().sum()

np.int64(0)

### 4. Remove the NaN values from Dataset

In [88]:
# It will show us any duplicate value we have
data.isna().sum()

BrandName    0
Details      0
Sizes        0
MRP          0
SellPrice    0
Discount     0
Category     0
dtype: int64

In [89]:
# So we don't have any NULL values But if we have we can remove by this
data.dropna(inplace=True)

### 5. Check for some more transformation

In [90]:
data.reset_index(inplace=True)

In [91]:
data.head()

,index,BrandName,Details,Sizes,MRP,SellPrice,Discount,Category
0,0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women

In [92]:
# delete old index columns
data.drop(columns="index", inplace=True)

In [93]:
# In Sizes column there are nan value but it didn't appeared because these are string
data["Sizes"][27929]

'Nan'

In [94]:
# SO rename them to NA VALUED
data["Sizes"] = data["Sizes"].replace("Nan" , "NA VALUED")

In [95]:
# Now remove these rows
data = data[data["Sizes"] != "NA VALUED"]

In [96]:
data

,BrandName,Details,Sizes,MRP,SellPrice,Discount,Category
0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women
...,...,...,...,...,...,...,...
24344,swiss eagle,womens analogue metallic watch,Size:Error Size,Rs\n13990,4197,70% off,Watches-Women
24731,lawman watches,womens rose gold dial stainless steel analogue...,Size:Error Size,Rs\n7499,4999,33% off,Watches-Women
25791,lawman watches,womens silver dial stainless steel analogue wa...,Size:Error Size,Rs\n5999,3999,33% off,Watches-Women
26028,miu miu,eau de parfum - 50 ml,Size:Error Size,Nan,6100,Nan,Fragrance-Women
26078,miu miu,eau de parfum - 30 ml,Size:Error Size,Nan,4400,Nan,Fragrance-Women

In [97]:
# In Discount column there are also Nan values , meaning it doesn't have any discount
# SO rename them to No Discount
data["Discount"] = data["Discount"].replace("Nan" , "No Discount")
data

,BrandName,Details,Sizes,MRP,SellPrice,Discount,Category
0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women
...,...,...,...,...,...,...,...
24344,swiss eagle,womens analogue metallic watch,Size:Error Size,Rs\n13990,4197,70% off,Watches-Women
24731,lawman watches,womens rose gold dial stainless steel analogue...,Size:Error Size,Rs\n7499,4999,33% off,Watches-Women
25791,lawman watches,womens silver dial stainless steel analogue wa...,Size:Error Size,Rs\n5999,3999,33% off,Watches-Women
26028,miu miu,eau de parfum - 50 ml,Size:Error Size,Nan,6100,No Discount,Fragrance-Women
26078,miu miu,eau de parfum - 30 ml,Size:Error Size,Nan,4400,No Discount,Fragrance-Women

In [98]:
# Size column also have Size:Error Size , so replce it with No Size
data["Sizes"] = data["Sizes"].replace("Size:Error Size" , "No Size")
data

,BrandName,Details,Sizes,MRP,SellPrice,Discount,Category
0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women
...,...,...,...,...,...,...,...
24344,swiss eagle,womens analogue metallic watch,No Size,Rs\n13990,4197,70% off,Watches-Women
24731,lawman watches,womens rose gold dial stainless steel analogue...,No Size,Rs\n7499,4999,33% off,Watches-Women
25791,lawman watches,womens silver dial stainless steel analogue wa...,No Size,Rs\n5999,3999,33% off,Watches-Women
26028,miu miu,eau de parfum - 50 ml,No Size,Nan,6100,No Discount,Fragrance-Women
26078,miu miu,eau de parfum - 30 ml,No Size,Nan,4400,No Discount,Fragrance-Women

In [99]:
data["MRP"]

0         Rs\n1699
1         Rs\n3499
2         Rs\n1199
3         Rs\n2299
4         Rs\n1699
           ...
24344    Rs\n13990
24731     Rs\n7499
25791     Rs\n5999
26028          Nan
26078          Nan
Name: MRP, Length: 22687, dtype: str

In [100]:
# MRP also has Nan values so in it we can fill Mean of all values
# first convert MRP values to int
data["MRP"] = data["MRP"].replace("Nan", "00000")
data["MRP"] = data["MRP"].str[3:]

In [101]:
data["MRP"] = data["MRP"].astype(int)

In [102]:
replaceval = data["MRP"].mean()
data["MRP"] = data["MRP"].apply(lambda x : int(replaceval) if x == 0 else int(x))

In [103]:
data["MRP"]

0         1699
1         3499
2         1199
3         2299
4         1699
         ...
24344    13990
24731     7499
25791     5999
26028     1698
26078     1698
Name: MRP, Length: 22687, dtype: int64

In [104]:
data.head()

,BrandName,Details,Sizes,MRP,SellPrice,Discount,Category
0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",1699,849,50% off,Westernwear-Women
1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",3499,2449,30% off,Westernwear-Women
2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",1199,599,50% off,Westernwear-Women
3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",2299,1379,40% off,Westernwear-Women
4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",1699,849,50% off,Westernwear-Women

In [ ]:
# Save the File
data.to_csv("cleaned_data.csv")