**TMBD webiste has APIs by which you can get movies realted data**

In [23]:
import pandas
import requests

In [33]:
# in the last of url we have mentioned page=1 means we want to get page 1 data
url = "https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1"
response = requests.get(url)

In [ ]:
response.json()['results']

In [26]:
df1 = pd.DataFrame(response.json()['results'])[['id', 'title', 'overview', 'release_date', 'popularity']]

In [27]:
df1.head()

,id,title,overview,release_date,popularity
0,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,32.4485
1,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,68.1406
2,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,83.1410
3,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,125.8724
4,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,38.2677

In [28]:
df1.shape

(20, 5)

**Till here we only got page 1 data from Api But there are 428 different pages so we have to run a loop and get data from all pages and append in one data Frame**

In [35]:
df = pd.DataFrame()

for i in range(1,429):
    url = f"https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={i}"
    response = requests.get(url)
    temp_df = pd.DataFrame(response.json()['results'])[['id', 'title', 'overview', 'release_date', 'popularity']]
    df = pd.concat([df, temp_df], ignore_index=True)

In [36]:
df.head()

,id,title,overview,release_date,popularity
0,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,32.4485
1,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,68.1406
2,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,83.1410
3,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,125.8724
4,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,38.2677

In [37]:
df.shape

(8560, 5)