**Finding Missing Data**

In [ ]:
import numpy as np 
import pandas as pd 

# Search = .isna()
# drop = .dropna()
# Fill = .fillna()

In [2]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [5]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [8]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [10]:
# check if columns have any NULL value
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

**Removing Missing Data**

In [11]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
# .dropna()  work on row basis, it will drop row if it is containing any NULL val
df.dropna()
# it will not change in original data frame, just return a snapshot
# to do inplace make inplace=True

     A  B    C    D
0  1.0  1  1.0  1.0

In [15]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [18]:
df.dropna(thresh=2) #thresh meaning there must be 2 non null values in each row, if any row doesn't have 2 non NULL it will remove that row

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

**Filling the missing Data**

In [105]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [24]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [27]:
# in column A it will fill 0, in B will fill 100 ...
vals = {"A":0 , "B":100, "C":200, "D":300}
df.fillna(value = vals)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  300.0
2  0.0  3    3.0  300.0
3  4.0  4  200.0  300.0
4  5.0  5  200.0    5.0

In [23]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [28]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0