In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv(r"netflix-data.csv")

In [ ]:
df = pd.DataFrame(data)
df

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"
...,...,...,...,...,...,...,...,...,...,...
8785,s8797,TV Show,Yunus Emre,Not Given,Turkey,1/17/2017,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"
8786,s8798,TV Show,Zak Storm,Not Given,United States,9/13/2018,2016,TV-Y7,3 Seasons,Kids' TV
8787,s8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,12/15/2016,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,s8784,TV Show,Yoko,Not Given,Pakistan,6/23/2018,2016,TV-Y,1 Season,Kids' TV
8789,s8786,TV Show,YOM,Not Given,Pakistan,6/7/2018,2016,TV-Y7,1 Season,Kids' TV

In [5]:
df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   str
 1   type          8790 non-null   str
 2   title         8790 non-null   str
 3   director      8790 non-null   str
 4   country       8790 non-null   str
 5   date_added    8790 non-null   str
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   str
 8   duration      8790 non-null   str
 9   listed_in     8790 non-null   str
dtypes: int64(1), str(9)
memory usage: 686.8 KB

## Steps we do to clean data
1. Deleting Redundant columns
2. Renaming Columns
3. Dropping Duplicates
4. Remove the NaN values from Dataset
5. Check for some more transformation
---

### 1. Deleting Redundant columns

In [ ]:
# Now we check if there is any redundant columns
data.columns

Index(['show_id', 'type', 'title', 'director', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in'],
      dtype='str')

In [16]:
df.head()

,show_id,type,title,director,country,date_added,release_year,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,125 min,"Dramas, Independent Movies, International Movies"

In [ ]:
# We can drop rating
df.drop(columns=["rating"], inplace=True)

### 2. Renaming Columns

In [17]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'country', 'date_added',
       'release_year', 'duration', 'listed_in'],
      dtype='str')

In [18]:
# we make a dictionary with -- orgName : newName
new_names = {}
for i in data.columns:
    new_names[i] = i.replace("_"," ").title()
print(new_names)

{'show_id': 'Show Id', 'type': 'Type', 'title': 'Title', 'director': 'Director', 'country': 'Country', 'date_added': 'Date Added', 'release_year': 'Release Year', 'rating': 'Rating', 'duration': 'Duration', 'listed_in': 'Listed In'}

In [ ]:
# now replace old names with new ones
data.rename(columns=new_names, inplace=True)
data

In [31]:
df = pd.DataFrame(data)

### 3. Dropping Duplicates

In [ ]:
# Check if there's any duplicate rows
data.duplicated().sum()
# It says 0 mean we don't have any duplicate rows

np.int64(0)

In [ ]:
# In this case w don't have any duplicates
# But if we do have we can remove those using

data.drop_duplicates(inplace=True)

### 4. Check for NULL Values

In [26]:
data.isna().sum()

Show Id         0
Type            0
Title           0
Director        0
Country         0
Date Added      0
Release Year    0
Rating          0
Duration        0
Listed In       0
dtype: int64

In [ ]:
# it shows we don't have any null values
# but if we have, we can remove those using

data.dropna(inplace=True)

### 5. Check for some more transformation

In [27]:
data.columns

Index(['Show Id', 'Type', 'Title', 'Director', 'Country', 'Date Added',
       'Release Year', 'Rating', 'Duration', 'Listed In'],
      dtype='str')

In [ ]:
# nunique tells us total unique values in a particular column
data["Show Id"].nunique()

8790

In [32]:
# Meaning we don't have duplicates in it
# But in Show Id values are string we have to make them integer
df["Show Id"].head()

0     s1
1     s3
2     s6
3    s14
4     s8
Name: Show Id, dtype: str

In [34]:
# Remove 's'
data["Show Id"] = data["Show Id"].apply(lambda x : x[1:])

In [36]:
# convert into integer
data["Show Id"] = data["Show Id"].astype(int)

In [37]:
data["Show Id"]

0          1
1          3
2          6
3         14
4          8
        ...
8785    8797
8786    8798
8787    8801
8788    8784
8789    8786
Name: Show Id, Length: 8790, dtype: int64

In [39]:
data["Date Added"]

0        9/25/2021
1        9/24/2021
2        9/24/2021
3        9/22/2021
4        9/24/2021
           ...
8785     1/17/2017
8786     9/13/2018
8787    12/15/2016
8788     6/23/2018
8789      6/7/2018
Name: Date Added, Length: 8790, dtype: str

In [41]:
# Date have '/' this symbol , we have to change it with '-'
data["Date Added"] = data["Date Added"].apply(lambda i : i.replace("/", "-"))

In [42]:
data

,Show Id,Type,Title,Director,Country,Date Added,Release Year,Rating,Duration,Listed In
0,1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9-25-2021,2020,PG-13,90 min,Documentaries
1,3,TV Show,Ganglands,Julien Leclercq,France,9-24-2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,6,TV Show,Midnight Mass,Mike Flanagan,United States,9-24-2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9-22-2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,8,Movie,Sankofa,Haile Gerima,United States,9-24-2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"
...,...,...,...,...,...,...,...,...,...,...
8785,8797,TV Show,Yunus Emre,Not Given,Turkey,1-17-2017,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"
8786,8798,TV Show,Zak Storm,Not Given,United States,9-13-2018,2016,TV-Y7,3 Seasons,Kids' TV
8787,8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,12-15-2016,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,8784,TV Show,Yoko,Not Given,Pakistan,6-23-2018,2016,TV-Y,1 Season,Kids' TV
8789,8786,TV Show,YOM,Not Given,Pakistan,6-7-2018,2016,TV-Y7,1 Season,Kids' TV

In [ ]:
#  Now Save this data
data.to_csv("cleaned_data.csv")